//
//  constantes.h
//  Compilador
//
//  Created by Arthur Fonseca on 9/22/11.
//  Copyright 2011 Poli USP. All rights reserved.
//

//#define PATH_PARA_ARQUIVO_FONTE "D:/vinicius/teste.txt"
//#define PATH_PARA_ARQUIVO_DE_PALAVRAS_RESERVADAS "D:/vinicius/palavrasreservadas.txt"
//#define PATH_PARA_ARQUIVO_DE_OPERADORES "D:/vinicius/operadores.txt"

<<<<<<< HEAD

#define PATH_PARA_ARQUIVO_FONTE "/Users/arthurgfonseca/Sites/Compilador/Compilador/ENTRADA.txt"
#define PATH_PARA_ARQUIVO_DE_PALAVRAS_RESERVADAS "/Users/arthurgfonseca/Sites/Compilador/Compilador/Compilador/palavrasreservadas.txt"
#define PATH_PARA_ARQUIVO_DE_OPERADORES "/Users/arthurgfonseca/Sites/Compilador/Compilador/Compilador/operadores.txt"

//#define PATH_PARA_ARQUIVO_FONTE "/Volumes/Pessoal/vinicius/ENTRADA.txt"
//#define PATH_PARA_ARQUIVO_DE_PALAVRAS_RESERVADAS "/Volumes/Pessoal/vinicius/palavrasreservadas.txt"
//#define PATH_PARA_ARQUIVO_DE_OPERADORES "/Volumes/Pessoal/vinicius/operadores.txt"

=======
#define PATH_PARA_ARQUIVO_FONTE "/Volumes/Pessoal/vinicius/ENTRADA.txt"
#define PATH_PARA_ARQUIVO_MVN "/Volumes/Pessoal/vinicius/SAIDA.txt"
#define PATH_PARA_ARQUIVO_DE_PALAVRAS_RESERVADAS "/Volumes/Pessoal/vinicius/palavrasreservadas.txt"
#define PATH_PARA_ARQUIVO_DE_OPERADORES "/Volumes/Pessoal/vinicius/operadores.txt"
>>>>>>> dev-vinicius

//#define PATH_PARA_ARQUIVO_DE_PALAVRAS_RESERVADAS "/Users/arthurgfonseca/Sites/Compilador/Compilador/Compilador/palavrasreservadas.txt"
//#define PATH_PARA_ARQUIVO_DE_OPERADORES "/Users/arthurgfonseca/Sites/Compilador/Compilador/Compilador/operadores.txt"

#define TRUE 1
#define FALSE 0

#define ESPACONULO 0
#define TABULACAO 9
#define LINE_FEED 10
#define CARRIAGE_RETURN 13
#define WHITE_SPACE 32

//
// Definicao dos tipos de tokens
//

#define PALAVRA 300
#define INTEIRO 301
#define FLOAT 302
#define DOUBLE 303

#define PALAVRARESERVADA 400
#define OPERADOR 401
#define SIMBOLO 402
#define STRING 403
#define OPERADOR_OU 404

#define PALAVRARESERVADA_auto 1001
#define PALAVRARESERVADA_break 1002
#define PALAVRARESERVADA_case 1003
#define PALAVRARESERVADA_char 1004
#define PALAVRARESERVADA_const 1005
#define PALAVRARESERVADA_continue 1006
#define PALAVRARESERVADA_default 1007
#define PALAVRARESERVADA_do 1008
#define PALAVRARESERVADA_double 1009
#define PALAVRARESERVADA_else 1010
#define PALAVRARESERVADA_enum 1011
#define PALAVRARESERVADA_extern 1012
#define PALAVRARESERVADA_float 1013
#define PALAVRARESERVADA_for 1014
#define PALAVRARESERVADA_goto 1015
#define PALAVRARESERVADA_if 1016
#define PALAVRARESERVADA_endif 1017
#define PALAVRARESERVADA_int 1018
#define PALAVRARESERVADA_long 1019
#define PALAVRARESERVADA_register 1020
#define PALAVRARESERVADA_return 1021
#define PALAVRARESERVADA_short 1022
#define PALAVRARESERVADA_signed 1023
#define PALAVRARESERVADA_sizeof 1024
#define PALAVRARESERVADA_static 1025
#define PALAVRARESERVADA_struct 1026
#define PALAVRARESERVADA_switch 1027
#define PALAVRARESERVADA_typedef 1028
#define PALAVRARESERVADA_union 1029
#define PALAVRARESERVADA_unsigned 1030
#define PALAVRARESERVADA_void 1031
#define PALAVRARESERVADA_volatile 1032
#define PALAVRARESERVADA_while 1033
#define PALAVRARESERVADA_endwhile 1034
#define PALAVRARESERVADA_program 1035
#define PALAVRARESERVADA_execute 1036
#define PALAVRARESERVADA_endprogram 1037
#define PALAVRARESERVADA_enddeclare 1038
#define PALAVRARESERVADA_scan 1039
#define PALAVRARESERVADA_print 1040
#define PALAVRARESERVADA_declare 1041

#define ACAOSEMANTICA_INICIO_DO_PROGRAMA 0
#define ACAOSEMANTICA_INICIO_DO_DECLARE 1
#define ACAOSEMANTICA_INICIO_DO_EXECUTE 2
#define ACAOSEMANTICA_DECLARACAO_DE_VARIAVEL 3
#define ACAOSEMANTICA_COMANDO_LE_SIMBOLO 4
#define ACAOSEMANTICA_COMANDO_ATRIBUICAO_DE_VARIAVEL_FIM 5
#define ACAOSEMANTICA_EXPRESSAO_LE_SIMBOLO 6
#define ACAOSEMANTICA_EXPRESSAO_LE_INTEIRO 7
#define ACAOSEMANTICA_EXPRESSAO_LE_ABRE_PARENTESES 8
#define ACAOSEMANTICA_EXPRESSAO_LE_FECHA_PARENTESES 9
#define ACAOSEMANTICA_EXPRESSAO_LE_OPERADOR_ARITMETICO 10
#define ACAOSEMANTICA_EXPRESSAO_FIM 11
#define ACAOSEMANTICA_COMANDO_FIM 12
#define ACAOSEMANTICA_FIM_DO_PROGRAMA 13
#define ACAOSEMANTICA_EXPRESSAO_LE_OPERADOR_COMPARACAO 14
#define ACAOSEMANTICA_EXPRESSAO_LE_OPERADOR_COMPARACAO_MAIOR 15
#define ACAOSEMANTICA_EXPRESSAO_LE_OPERADOR_COMPARACAO_MENOR 16
#define ACAOSEMANTICA_EXPRESSAO_LE_OPERADOR_COMPARACAO_IGUAL 17
#define ACAOSEMANTICA_COMANDO_IF_INICIO 18
#define ACAOSEMANTICA_COMANDO_IF_INICIO_THEN 19
#define ACAOSEMANTICA_EXPRESSAO_LE_OPERADOR_COMPARACAO_MAIOR_IGUAL 20
#define ACAOSEMANTICA_EXPRESSAO_LE_OPERADOR_COMPARACAO_MENOR_IGUAL 21
#define ACAOSEMANTICA_EXPRESSAO_LE_OPERADOR_COMPARACAO_DIFERENTE 22
#define ACAOSEMANTICA_COMANDO_IF_FIM_COM_ELSE 23
#define ACAOSEMANTICA_COMANDO_IF_FIM_SEM_ELSE 24
#define ACAOSEMANTICA_COMANDO_IF_INICIO_ELSE 25
#define ACAOSEMANTICA_COMANDO_WHILE_INICIO 26
#define ACAOSEMANTICA_COMANDO_WHILE_DENTRO 27
#define ACAOSEMANTICA_COMANDO_WHILE_FIM 28
#define ACAOSEMANTICA_DECLARACAO_DE_FUNCAO_INICIO 29
#define ACAOSEMANTICA_DECLARACAO_DE_FUNCAO_COMANDOS 30
#define ACAOSEMANTICA_DECLARACAO_DE_FUNCAO_FIM 31
#define ACAOSEMANTICA_DECLARACAO_DE_FUNCAO_NOME 32
